import { QuartzComponent, QuartzComponentProps } from "../types"
import { resolveRelative, FullSlug } from "../../util/path"
import {
  buildNoteSummaries,
  computeStats,
  groupByFolder,
  sortByCreatedDesc,
  formatDate,
} from "../../plugins/directories/notes"
import { toCandidates } from "../../plugins/recap/due"
import { RecapRail } from "../../plugins/recap/components"

const GRAPH_MINI_CFG = {
  depth: -1,
  scale: 0.9,
  repelForce: 0.5,
  centerForce: 0.25,
  linkDistance: 30,
  fontSize: 0.6,
  opacityScale: 1,
  showTags: false,
  removeTags: [] as string[],
  drag: false,
  zoom: false,
  focusOnHover: true,
}

/**
 * Homepage body — generated by the `directories` local plugin at slug
 * "index" (it wins over ContentPage via a higher pageType priority; see that
 * plugin's index.ts). Everything here is computed at build time from
 * `allFiles`; the only client-side piece is the "due for a recap" rail,
 * which RecapRail renders as a skeleton for quiz.inline.ts to hydrate.
 */
const Homepage: QuartzComponent = (props: QuartzComponentProps) => {
  const { fileData, allFiles } = props
  const slug = fileData.slug!
  const notes = buildNoteSummaries(allFiles)
  const stats = computeStats(notes)
  const recent = sortByCreatedDesc(notes).slice(0, 7)
  const folders = groupByFolder(notes).slice(0, 8)
  const candidates = toCandidates(notes)

  const title = (fileData.frontmatter?.title as string) ?? "Journal"
  const description =
    fileData.description ||
    "One idea per note, written the day I hit it. Everything here links to something else, which is the whole point of keeping it."

  const graphHref = resolveRelative(slug, "graph" as FullSlug)
  const foldersHref = resolveRelative(slug, "folders" as FullSlug)
  const startHref = recent[0] ? resolveRelative(slug, recent[0].slug as FullSlug) : graphHref

  const maxBucket = Math.max(1, ...stats.activity)

  return (
    <article class="popover-hint bp-homepage">
      <section class="bp-hero">
        <div class="bp-hero-main">
          <div class="bp-eyebrow">Platform engineering · working notes</div>
          <h1>{title}</h1>
          <p>{description}</p>
          <div class="bp-hero-actions">
            <a class="blueprint bp-btn bp-btn-primary" href={graphHref}>
              <i class="corner tl"></i>
              <i class="corner tr"></i>
              <i class="corner bl"></i>
              <i class="corner br"></i>
              Open the graph
            </a>
            <a class="bp-btn" href={startHref}>
              Read the latest note
            </a>
          </div>
        </div>
        <div class="bp-stats-rail">
          <div class="bp-stat">
            <span class="bp-stat-label">Notes</span>
            <span class="bp-stat-value">{stats.noteCount}</span>
          </div>
          <div class="bp-stat">
            <span class="bp-stat-label">Links</span>
            <span class="bp-stat-value">{stats.linkCount}</span>
          </div>
          <div class="bp-stat">
            <span class="bp-stat-label">Tags</span>
            <span class="bp-stat-value">{stats.tagCount}</span>
          </div>
          <div class="bp-stat">
            <span class="bp-stat-label">Week streak</span>
            <span class="bp-stat-value">{stats.weekStreak}</span>
          </div>
          <div class="bp-activity-chart">
            <div class="bp-label">Weeks written · 26</div>
            <div class="bp-activity-bars">
              {stats.activity.map((count) => {
                const level = count === 0 ? undefined : count >= maxBucket ? "high" : "mid"
                const h = count === 0 ? 3 : Math.max(4, Math.round((count / maxBucket) * 44))
                return (
                  <div
                    class="bp-activity-bar"
                    data-level={level}
                    style={{ height: `${h}px` }}
                  ></div>
                )
              })}
            </div>
          </div>
        </div>
      </section>

      <section class="bp-graph-section">
        <div class="bp-section-head">
          <h2>The graph</h2>
          <a class="bp-section-link" href={graphHref}>
            Full view →
          </a>
        </div>
        <div class="blueprint bp-graph-panel bp-graph-mini">
          <i class="corner tl"></i>
          <i class="corner tr"></i>
          <i class="corner bl"></i>
          <i class="corner br"></i>
          <div class="graph-container" data-cfg={JSON.stringify(GRAPH_MINI_CFG)}></div>
          <div class="bp-graph-caption">
            {stats.noteCount} NOTES · {stats.linkCount} LINKS
            <br />
            CLICK A NODE TO READ IT
          </div>
        </div>
      </section>

      <section class="bp-two-col">
        <div class="bp-recent-main">
          <h2>Recently written</h2>
          <div class="bp-label">newest first, across every folder</div>
          <ul class="bp-recent-list">
            {recent.map((n) => (
              <li>
                <a class="bp-recent-row" href={resolveRelative(slug, n.slug as FullSlug)}>
                  <span class="bp-recent-date">{formatDate(n.created)}</span>
                  <div>
                    <div class="bp-recent-title">{n.title}</div>
                    {n.description && <div class="bp-recent-blurb">{n.description}</div>}
                  </div>
                  <span class="bp-folder-chip">{n.folderLabel}</span>
                </a>
              </li>
            ))}
          </ul>
        </div>
        <aside class="bp-aside">
          <h6 class="bp-label">Due for a recap</h6>
          <RecapRail {...props} candidates={candidates} />
          <h6 class="bp-label" style="margin-top: 1.75rem">
            Folders
          </h6>
          <ul class="bp-folder-rows">
            {folders.map((g) => (
              <li>
                <a
                  class="bp-folder-row"
                  href={resolveRelative(slug, `${g.folder}/index` as FullSlug)}
                >
                  <span class="bp-folder-row-name">{g.label}</span>
                  <span class="bp-folder-row-count">{g.notes.length}</span>
                </a>
              </li>
            ))}
          </ul>
          <a class="bp-section-link" href={foldersHref}>
            All folders →
          </a>
        </aside>
      </section>
    </article>
  )
}

export default Homepage
